contact/urls.py
from django.urls import path
from . import views

app_name="contact"
urlpatterns=[path("contact/",views.test,name="test")]

data_analysis/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.auth import login,logout

urlpatterns = [
    path('data_record/',include("data_record.urls")),
    path('contact/',include("contact.urls")),
    path('admin/', admin.site.urls),
    path('accounts/login/',login),
    path('accounts/logout/',logout),
]

data_record/urls.py
from django.urls import path
from . import views



app_name="data_record"
urlpatterns=[path('',views.home_page,name="home_page"),
             path('log_in/',views.log_in,name="log_in"),
             path('check_passwd/',views.check_passwd,name="check_passwd"),
             path('data_analysis/',views.data_analysis,name="data_analysis"),
             path('display/',views.display,name="display"),
             path('contact/',views.contact,name="contact"),
             path('search-form/',views.search_form,name="search_form"),
             path('search/',views.search,name="search"),
             path('upload/',views.upload,name="upload"),
             path('upload_file/',views.upload,name="upload"),
             path('<int:History_id>/',views.detail,name="detail"),
             path('<int:History_id>/result/',views.result,name="result"),
             path('<int:History_id>/vote/',views.vote,name="vote"),
             path(r'add/<year:num_n>/',views.time_add,name="time_add")
]

data_record/models.py
from django.db import models
import datetime
from django.utils import timezone
#coding=utf-8
#定义一个数据库来储存所有的用户的用户名和密码
class Users(models.Model):
    user_name=models.CharField(max_length=30)
    user_password=models.CharField(max_length=40)
    use_email=models.EmailField()
# Create your models here.
#定义项目的列表，包括以下内容（项目名称，项目负责人，项目立项时间）
class Project(models.Model):
    project_name=models.CharField(max_length=20)
    person=models.CharField(max_length=20,blank=True)
    release_date=models.DateTimeField("date released",blank=True)
    def __str__(self):
        return self.project_name

#定义分析的路径历史，历史包括几个内容（文件夹名称，项目名称，分析日期，分析人）
class History(models.Model):
    #定义分析的文件夹名称
    folder_name=models.CharField(max_length=300)
    #定义分析的路径
    path_n=models.CharField(max_length=500)
    #定义分析的项目
    #project_name=models.CharField(max_length=20,default="000000")
    project_name=models.ForeignKey(Project,on_delete=models.CASCADE)
    #定义分析的时间
    pub_date=models.DateTimeField("date analyzed")
    #定义分析的人
    person_analysis=models.CharField(max_length=300) 
    def __str__(self):
        return self.folder_name
    def was_analyzed_recently(self):
        return self.pub_date>=timezone.now()-datetime.timedelta(days=1)

        

data_record/forms.py
from django import forms
class ContactForms(forms.Form):
    subject=forms.CharField(max_length=100)
    email=forms.EmailField(required=False,label="your e-mail address")
    message=forms.CharField(widget=forms.Textarea)
    def clean_message(self):
        message=self.cleaned_data["message"]
        num_words=len(message.split())
        if num_words<4:
            raise forms.ValidationError("not enough words!")
        return message
    
    

contact/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404
from django.template import loader

def test(request):
        return HttpResponse("testtttttttttttttttttt")

data_record/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,FileResponse
from django.template import loader
import datetime
from data_record.forms import ContactForms
# Create your views here.
from .models import History,Project,Users
import os
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
#定义一个登陆的界面
def log_in(request):
    if request:
        request.session.set_test_cookie()
        return render(request,"data_record/login.html",{"error":""})
def check_passwd(request):
    if request.method=="POST":
        #print(request.session.test_cookie_worked()) 
        username=request.POST.get("name")
        password=request.POST.get("passwd")
        #if request.session.test_cookie_worked():
        user=authenticate(username=username,password=password)
        if user is not None:
            return render(request,"data_record/function_choose.html")
        else:
            #return HttpResponse("error")
            return render(request,"data_record/login.html",{"error":"wrong password or username,please check and relogin"})
        #try:
            #m=Member.object.get(user_name=requst.POST["username"])
            #判断密码是否相同
            #username = request.POST.get("name")
            #password = request.POST.get("passwd")
            #if m.password==request.POST["password"]:
            #    request.session["member_id"]=m.id
            #    return HttpResponse("ok you are logging in ")
        #except KeyError:
        #    return HttpResponse("something wrong")
    else:
        return HttpResponse("not login")
        #username=request.post.get("username")
        #e = .objects.filter(email=email).first()
        #user=auth(username="1234",password=password)
        #user=request.user.is_authenticated
        #if username=="fanxuezhe" and password=="123455":
        #if user:
        #    #return render(request,"data_record/upload.html")
        #    return HttpResponse(user)
        #else:
        #    return HttpResponse("wrong number %s   %s "%(username,password))
#def index(request):
#    return HttpResponse("hello,this is the place record the data analysis history")
#定义一个function，该function的功能是指定数据分析的界面
def data_analysis(request):
    render(request,"data_record/data_analysis.html",)
#展示历史数据
def display(request):
    historys=History.objects.order_by("folder_name")
    history_values=historys.values()
    char_list=[]
    [[char_list.append("\t".join([key_n,str(value_n)]))for key_n,value_n in dict_n.items()] for dict_n in history_values] 
    return render(request,"data_record/show_record.html",{"display_data":char_list})
#定义一个homepage的视图,这将会是一个登陆界面
def home_page(request):
    #render(request,"data_record/home_page.html")
    now=datetime.datetime.now()
    target_url="<html><body>it is now %s</body></html>"%now
    #return HttpResponse(target_url)
    path_list=["path_1","path_2","path_3","path_4"]
    html=[]
    #for k,v in request.META.items():
    #    html.append("<tr><td>%s</td><td>%s</td></tr>"%(k,v))
    #return render(request,"data_record/home_page.html",{"path_all":path_list})
    #return HttpResponse("\n".join(html))
    return render(request,"data_record/show_info.html",{"all_info":request.META.items()})
def contact(request):
    if request.method=="POST":
        form=ContactForms(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            #send_email(cd["subject"],cd["message"],cd.get["email","noreply@example.com"],["siteowner@example.com"])
            #return HttpResponseRedirect("search-form/")
            return HttpResponse("another website")
    else:
        form=ContactForms(initial={"subject":"I love your site!"})
    return render(request,"data_record/contact_form.html",{"form":form})
        
       
        
def time_add(request,num_n):
    #num_n=100
    time_now=datetime.datetime.now()
    try:
        int_num=int(num_n)
    except:
        raise Http404
    else:
        time_add=time_now+datetime.timedelta(hours=int_num)
        html='<html><body> this is time %s </body></html>'%time_add
        return HttpResponse(html)
#@login_required
def upload(request):
    if request.method=="POST":
    
        #首先检查当前是否是一个授权的状态（是否已经登陆）
    #if request.user.is_authenticated:
    #    return HttpResponse("%s you are thenticated"%request.user.username)
    #else:
    #    return HttpResponse("%s   dxError "%request.user.username)
        
        #获取当前的分析人和分析的日期，根据这个来创建文件夹储存文件
        username=request.user
        
        #定义文件储存的目录
        dir_store=r"/home/fanxuezhe/files/test_files/django_download"
        #获取post中的文件
        myFile=request.FILES.get("myfile")
        if myFile :
            #return HttpResponse(myFile.name)
            copied_file=os.path.join(dir_store,myFile.name)
            with open(copied_file,"wb") as f:
                for content_n in myFile.chunks():
                    f.write(content_n)
            
            #接下来解压文件并且进行分析
            os.chdir(dir_store)
            all_files=os.listdir(dir_store)
            #解压上传的文件
            os.system("unzip %s >>log_file"%myFile.name)
            os.system("multi_tools FGS .")
            os.chdir(myFile.name.strip(".zip"))
            all_files=os.listdir(os.getcwd())
            
            #os.system("multi_tools FGS . >>logfile")
            #os.system("compress_result . >>logfile")
            #os.system("tar -czvf final_result.tar.gz logfile all_result.tar.gz")
            
            #log_file=open(os.path.join(dir_store,"logfile"),"wb")
            #result_file=open(os.path.join(dir_store,"final_result"),"rb")
            #file_response=FileResponse(result_file)
            #file_response["content_type"]="application/octet_stream"
            #file_response["Content-Disposition"]='attachment;file=result_file'
            #return HttpResponse("all over")
            return HttpResponse("\n".join(all_files))

        else:
            return HttpResponse("none file get")
        #if  myFile:
        #    f=open(r"/home/fanxuezhe/copied_{}".format(myFile.name),"wb")
        #    for line_n in file.chunks():
        #        f.write(line_n)
        #    f.close()
            #values.sorted()
        #    html=[]
            #for k,v in values:
            #    html.append("<tr><td>%s</td><td>%s</td></tr>"%(k,v))
            #    
            #return HttpResponse("<table>%s</table>"%("\n".join(html)))
            #list_values=[]
            #for key,value in values:
            #    list_values.append("%sxxxxxxxxxxxxx%s"%(key,value))
            #return render(request,"data_record/display_all.html",{"info_dict_items":list_values})
        #path_test=r"/home/fanxuezhe/files/test_files/django_test_files"
        #destination=open(os.path.join(path_test,myFile.name),"wb+")
        #for chunk in myFile.chunks():
        #    destination.write(chunk)
        #destination.close()
            
            #return HttpResponse("upload over")
        #else:
        #    return HttpResponse("can not get the file")
    else:
        return render(request,"data_record/upload.html") 
        
def search_form(request):
    if request.GET:
        if "q" in request.GET and request.GET["q"]:
        #message="ok,%s is found"%request.GET["q"]
            try:
                project=Project.objects.filter(project_name=request.GET["q"])
                message=project.project_name
            except:
                message="sorry,nnnnnnn not found"
            return HttpResponse(message)
        else:
            return render(request,"data_record/search_form.html",{"Search":"This is another search","warnings":"can not find or input in empty please check"})
    return render(request,"data_record/search_form.html",{"Search":"This is search","warnings":"the origin"})
        

def search(request):
    if "q" in request.GET and request.GET["q"]:
        #message="ok,%s is found"%request.GET["q"]
        try:
            project=Project.objects.filter(project_name=request.GET["q"])
            message=project.project_name
        except:
            message="sorry,nnnnnnn not found"
        return HttpResponse(message)
    else:
        return render(request,"data_record/search_form.html",{"Search":"This is another search","warnings":"can not find or input in empty please check"})
        

def index(request):
    latest_analysis_list=History.objects.order_by("-pub_date")[:3]
    #template=loader.get_template("data_record/index.html")
    #这里的键和templates中的变量名称是对应的
    context={"latest_analysis_list":latest_analysis_list}
    #output=",".join(q.project_name for q in latest_analysis_list)
    #前面放上请求，后面放上模板和变量
    return render(request,"data_record/index.html",context)

def detail(request,History_id):
    analysis=get_object_or_404(History,pk=History_id)
    return render(request,"data_record/detail.html",{"History":analysis})
#def detail(request,History_id):
#    return HttpResponse("hello you are checking detail of %s"%History_id)

#def detail(request,History_id):
#    try:
#        analysis=History.objects.get(pk=History_id)
#    except History.DoesNotExist:
#        raise Http404("There is no id called %d"%History_id)
#    return render(request,"data_record/detail.html",{"History":analysis})
    #return HttpResponse("hello you are checking detail of %s"%History_id)



def result(request,History_id):
    return HttpResponse("hello you are checking result of %s"%History_id)
def vote(request,History_id):
    return HttpResponse("hello you are checking vote of %s"%History_id)

data_record/templates/data_record/contact_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>
    {%if form.errors%}
    <p style="color:red;">
        please correct the errors {{form.errors|pluralize}} below
    </p>
    {%endif%}
    <form action="" method="post">
    {%csrf_token%}
    <table>{{form.as_table}}</table>
    <input type="submit" value="Submit">
    </form>
</body>
</html>

data_record/templates/data_record/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

data_record/templates/data_record/display_all.html
{% if info_dict_items %}
    <ul>
    {% for value in info_dict_items %}
    <li>{{value}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p> No information available</p>
{% endif %}

data_record/templates/data_record/download.html
<!DOCTYPE html>
<html>
<head>
    <title>download page</title>
    <meta charset="UTF-8">
</head>
    
    <h1>Congratulations! analysis finished</h1>
    <h2>Below is the result</h2>
    

</html>

data_record/templates/data_record/function_choose.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
<head>
    <title>choose function</title>
<head>
<body>
<form action="/data_record/check/" method="get" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="submit" value="check_data">
</form>

<form action="/data_record/download/" method="get" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="submit" value="download">
</form>

<form action="/data_record/upload/" method="get" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="submit" value="data_analysis">
</form>

</body>
</html>

data_record/templates/data_record/home_page.html
<!DOCTYPE html>
<html>
<head>
    <title> Home of data record!</title>
    <meta charset="UTF-8">
</head>
<body>
    {% for path_n in path_all %}
        
        <li>{{forloop.counter}}:{{path_n}}</li>
    {%endfor%}
</body>
</html>

data_record/templates/data_record/index.html
{% if latest_analysis_list %}
    <ul>
    {% for history in latest_analysis_list %}
        <li><a href="{% url 'data_record:detail'  history.id %}">{{ history.project_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

data_record/templates/data_record/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    {% if error %}
    <p>{{error}}</p>
    {% endif %}
    <form action="/data_record/check_passwd/" method="post">
        {% csrf_token %}
    <p>your name<input type="text" name ="name"></p>
    <p>your passwd <input type="password" name="passwd"></p>
    <input type="submit" value="提交">
    </form>
</body>
</html>

data_record/templates/data_record/search_form.html
<html>
<head>
    <title>{{Search}}</title>
</head>
<body>
    {%if warnings%}
    <p style="color:red;">{{warnings}}</p>
    {%endif%}
    <center>next is form</center>
    <form action="/data_record/contact/" method="get">
    {%csrf_token%}
    <p>Subject<input type="text" name="subject"></p>
    <p>your email(optional)<input type="text" name="email"></p>
    <p>messages<input type="text" name="message"></p>
    <input type="submit" value="Search">
    </form>
</body>
</html>

data_record/templates/data_record/show_info.html
<!DOCTYPE html>
<html>
<head>
    <title>show the info</title>
<head>
<body>
    {%for k,v in all_info%}
    <tr>{{k}}:{{v}}</tr>
    {%endfor%}
</body>
</html>

data_record/templates/data_record/show_record.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
<head>
    <title>display result path</title>
</head>
<body>
    
    {%if display_data %}
        <ul>
        {% for info_n in display_data %}
            <li>{{info_n}}</li>
        {% endfor %}
         
        <ul>
    {%endif%}
</body>
</html>

data_record/templates/data_record/upload.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
<head>
    <title>upload a file</title>
<head>
<body>
<form action="/data_record/upload/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <input type="submit" value="保存">
    </form>
</body>
</html>